services:
  shadowsocks-rust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ss-rust
    ports:
      - "${PORT}:${PORT}/tcp"
      - "${PORT}:${PORT}/udp"
    env_file: .env
    volumes:
      - type: bind
        source: ./config.json
        target: /etc/shadowsocks-rust/config.json
    restart: unless-stopped
