services:
  shadowsocks-rust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ss-rust
    ports:
      - "23333:23333/tcp"
      - "23333:23333/udp"
    volumes:
      - type: bind
        source: ./config.json
        target: /etc/shadowsocks-rust/config.json
    restart: unless-stopped
