name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the amd64 Docker image
      working-directory: ./amd64
      run: docker build . --file Dockerfile --tag cakrome/ss-rust:$(date +%s)
